# This file was generated by the Julia Swagger Code Generator
# Do not modify this file directly. Modify the swagger specification instead.

module Blob

using Random
using Dates
using HTTP
using Swagger
import Swagger: field_name, property_type, hasproperty, validate_property, SwaggerApi, SwaggerModel
import Base: convert, propertynames

include("modelincludes.jl")

include("api_BlobContainersApi.jl")
include("api_BlobServiceApi.jl")

# export models
export convert, BlobServiceItems
export convert, ChangeFeed
export convert, ContainerProperties
export convert, ImmutabilityPolicyProperties
export convert, ImmutabilityPolicyProperty
export convert, LeaseContainerRequest
export convert, LeaseContainerResponse
export convert, LegalHold
export convert, LegalHoldProperties
export convert, ListContainerItems
export convert, Resource
export convert, RestorePolicyProperties
export convert, TagProperty
export convert, UpdateHistoryProperty
export convert, AzureEntityResource
export convert, BlobServiceProperties
export convert, BlobContainer
export convert, ImmutabilityPolicy
export convert, ListContainerItem

# export operations
export convert, BlobContainersApi, BlobServiceApi

export check_required, field_name, property_type, hasproperty, propertynames, validate_property, convert

end
