# This file was generated by the Julia Swagger Code Generator
# Do not modify this file directly. Modify the swagger specification instead.


mutable struct RestorePolicyProperties <: SwaggerModel
    enabled::Any # spec type: Union{ Nothing, Bool } # spec name: enabled
    days::Any # spec type: Union{ Nothing, Int32 } # spec name: days
    lastEnabledTime::Any # spec type: Union{ Nothing, DateTime } # spec name: lastEnabledTime

    function RestorePolicyProperties(;enabled=nothing, days=nothing, lastEnabledTime=nothing)
        o = new()
        validate_property(RestorePolicyProperties, Symbol("enabled"), enabled)
        setfield!(o, Symbol("enabled"), enabled)
        validate_property(RestorePolicyProperties, Symbol("days"), days)
        setfield!(o, Symbol("days"), days)
        validate_property(RestorePolicyProperties, Symbol("lastEnabledTime"), lastEnabledTime)
        setfield!(o, Symbol("lastEnabledTime"), lastEnabledTime)
        o
    end
end # type RestorePolicyProperties

const _property_map_RestorePolicyProperties = Dict{Symbol,Symbol}(Symbol("enabled")=>Symbol("enabled"), Symbol("days")=>Symbol("days"), Symbol("lastEnabledTime")=>Symbol("lastEnabledTime"))
const _property_types_RestorePolicyProperties = Dict{Symbol,String}(Symbol("enabled")=>"Bool", Symbol("days")=>"Int32", Symbol("lastEnabledTime")=>"DateTime")
Base.propertynames(::Type{ RestorePolicyProperties }) = collect(keys(_property_map_RestorePolicyProperties))
Swagger.property_type(::Type{ RestorePolicyProperties }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_RestorePolicyProperties[name]))}
Swagger.field_name(::Type{ RestorePolicyProperties }, property_name::Symbol) =  _property_map_RestorePolicyProperties[property_name]

function check_required(o::RestorePolicyProperties)
    (getproperty(o, Symbol("enabled")) === nothing) && (return false)
    true
end

function validate_property(::Type{ RestorePolicyProperties }, name::Symbol, val)
    if name === Symbol("days")
        Swagger.validate_param(name, "RestorePolicyProperties", :maximum, val, 365, false)
        Swagger.validate_param(name, "RestorePolicyProperties", :minimum, val, 1, false)
    end
end
