# This file was generated by the Julia Swagger Code Generator
# Do not modify this file directly. Modify the swagger specification instead.


mutable struct ListContainerItem <: SwaggerModel
    id::Any # spec type: Union{ Nothing, String } # spec name: id
    name::Any # spec type: Union{ Nothing, String } # spec name: name
    type::Any # spec type: Union{ Nothing, String } # spec name: type

    function ListContainerItem(;id=nothing, name=nothing, type=nothing)
        o = new()
        validate_property(ListContainerItem, Symbol("id"), id)
        setfield!(o, Symbol("id"), id)
        validate_property(ListContainerItem, Symbol("name"), name)
        setfield!(o, Symbol("name"), name)
        validate_property(ListContainerItem, Symbol("type"), type)
        setfield!(o, Symbol("type"), type)
        o
    end
end # type ListContainerItem

const _property_map_ListContainerItem = Dict{Symbol,Symbol}(Symbol("id")=>Symbol("id"), Symbol("name")=>Symbol("name"), Symbol("type")=>Symbol("type"))
const _property_types_ListContainerItem = Dict{Symbol,String}(Symbol("id")=>"String", Symbol("name")=>"String", Symbol("type")=>"String")
Base.propertynames(::Type{ ListContainerItem }) = collect(keys(_property_map_ListContainerItem))
Swagger.property_type(::Type{ ListContainerItem }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_ListContainerItem[name]))}
Swagger.field_name(::Type{ ListContainerItem }, property_name::Symbol) =  _property_map_ListContainerItem[property_name]

function check_required(o::ListContainerItem)
    true
end

function validate_property(::Type{ ListContainerItem }, name::Symbol, val)
end
