# This file was generated by the Julia Swagger Code Generator
# Do not modify this file directly. Modify the swagger specification instead.


mutable struct ChangeFeed <: SwaggerModel
    enabled::Any # spec type: Union{ Nothing, Bool } # spec name: enabled

    function ChangeFeed(;enabled=nothing)
        o = new()
        validate_property(ChangeFeed, Symbol("enabled"), enabled)
        setfield!(o, Symbol("enabled"), enabled)
        o
    end
end # type ChangeFeed

const _property_map_ChangeFeed = Dict{Symbol,Symbol}(Symbol("enabled")=>Symbol("enabled"))
const _property_types_ChangeFeed = Dict{Symbol,String}(Symbol("enabled")=>"Bool")
Base.propertynames(::Type{ ChangeFeed }) = collect(keys(_property_map_ChangeFeed))
Swagger.property_type(::Type{ ChangeFeed }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_ChangeFeed[name]))}
Swagger.field_name(::Type{ ChangeFeed }, property_name::Symbol) =  _property_map_ChangeFeed[property_name]

function check_required(o::ChangeFeed)
    true
end

function validate_property(::Type{ ChangeFeed }, name::Symbol, val)
end
