# This file was generated by the Julia Swagger Code Generator
# Do not modify this file directly. Modify the swagger specification instead.


mutable struct BlobContainer <: SwaggerModel
    id::Any # spec type: Union{ Nothing, String } # spec name: id
    name::Any # spec type: Union{ Nothing, String } # spec name: name
    type::Any # spec type: Union{ Nothing, String } # spec name: type

    function BlobContainer(;id=nothing, name=nothing, type=nothing)
        o = new()
        validate_property(BlobContainer, Symbol("id"), id)
        setfield!(o, Symbol("id"), id)
        validate_property(BlobContainer, Symbol("name"), name)
        setfield!(o, Symbol("name"), name)
        validate_property(BlobContainer, Symbol("type"), type)
        setfield!(o, Symbol("type"), type)
        o
    end
end # type BlobContainer

const _property_map_BlobContainer = Dict{Symbol,Symbol}(Symbol("id")=>Symbol("id"), Symbol("name")=>Symbol("name"), Symbol("type")=>Symbol("type"))
const _property_types_BlobContainer = Dict{Symbol,String}(Symbol("id")=>"String", Symbol("name")=>"String", Symbol("type")=>"String")
Base.propertynames(::Type{ BlobContainer }) = collect(keys(_property_map_BlobContainer))
Swagger.property_type(::Type{ BlobContainer }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_BlobContainer[name]))}
Swagger.field_name(::Type{ BlobContainer }, property_name::Symbol) =  _property_map_BlobContainer[property_name]

function check_required(o::BlobContainer)
    true
end

function validate_property(::Type{ BlobContainer }, name::Symbol, val)
end
