# This file was generated by the Julia Swagger Code Generator
# Do not modify this file directly. Modify the swagger specification instead.


mutable struct ListContainerItems <: SwaggerModel
    value::Any # spec type: Union{ Nothing, Vector{ListContainerItem} } # spec name: value
    nextLink::Any # spec type: Union{ Nothing, String } # spec name: nextLink

    function ListContainerItems(;value=nothing, nextLink=nothing)
        o = new()
        validate_property(ListContainerItems, Symbol("value"), value)
        setfield!(o, Symbol("value"), value)
        validate_property(ListContainerItems, Symbol("nextLink"), nextLink)
        setfield!(o, Symbol("nextLink"), nextLink)
        o
    end
end # type ListContainerItems

const _property_map_ListContainerItems = Dict{Symbol,Symbol}(Symbol("value")=>Symbol("value"), Symbol("nextLink")=>Symbol("nextLink"))
const _property_types_ListContainerItems = Dict{Symbol,String}(Symbol("value")=>"Vector{ListContainerItem}", Symbol("nextLink")=>"String")
Base.propertynames(::Type{ ListContainerItems }) = collect(keys(_property_map_ListContainerItems))
Swagger.property_type(::Type{ ListContainerItems }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_ListContainerItems[name]))}
Swagger.field_name(::Type{ ListContainerItems }, property_name::Symbol) =  _property_map_ListContainerItems[property_name]

function check_required(o::ListContainerItems)
    true
end

function validate_property(::Type{ ListContainerItems }, name::Symbol, val)
end
