# This file was generated by the Julia Swagger Code Generator
# Do not modify this file directly. Modify the swagger specification instead.


mutable struct AzureEntityResource <: SwaggerModel
    id::Any # spec type: Union{ Nothing, String } # spec name: id
    name::Any # spec type: Union{ Nothing, String } # spec name: name
    type::Any # spec type: Union{ Nothing, String } # spec name: type

    function AzureEntityResource(;id=nothing, name=nothing, type=nothing)
        o = new()
        validate_property(AzureEntityResource, Symbol("id"), id)
        setfield!(o, Symbol("id"), id)
        validate_property(AzureEntityResource, Symbol("name"), name)
        setfield!(o, Symbol("name"), name)
        validate_property(AzureEntityResource, Symbol("type"), type)
        setfield!(o, Symbol("type"), type)
        o
    end
end # type AzureEntityResource

const _property_map_AzureEntityResource = Dict{Symbol,Symbol}(Symbol("id")=>Symbol("id"), Symbol("name")=>Symbol("name"), Symbol("type")=>Symbol("type"))
const _property_types_AzureEntityResource = Dict{Symbol,String}(Symbol("id")=>"String", Symbol("name")=>"String", Symbol("type")=>"String")
Base.propertynames(::Type{ AzureEntityResource }) = collect(keys(_property_map_AzureEntityResource))
Swagger.property_type(::Type{ AzureEntityResource }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_AzureEntityResource[name]))}
Swagger.field_name(::Type{ AzureEntityResource }, property_name::Symbol) =  _property_map_AzureEntityResource[property_name]

function check_required(o::AzureEntityResource)
    true
end

function validate_property(::Type{ AzureEntityResource }, name::Symbol, val)
end
