# This file was generated by the Julia Swagger Code Generator
# Do not modify this file directly. Modify the swagger specification instead.


mutable struct ImmutabilityPolicy <: SwaggerModel
    id::Any # spec type: Union{ Nothing, String } # spec name: id
    name::Any # spec type: Union{ Nothing, String } # spec name: name
    type::Any # spec type: Union{ Nothing, String } # spec name: type

    function ImmutabilityPolicy(;id=nothing, name=nothing, type=nothing)
        o = new()
        validate_property(ImmutabilityPolicy, Symbol("id"), id)
        setfield!(o, Symbol("id"), id)
        validate_property(ImmutabilityPolicy, Symbol("name"), name)
        setfield!(o, Symbol("name"), name)
        validate_property(ImmutabilityPolicy, Symbol("type"), type)
        setfield!(o, Symbol("type"), type)
        o
    end
end # type ImmutabilityPolicy

const _property_map_ImmutabilityPolicy = Dict{Symbol,Symbol}(Symbol("id")=>Symbol("id"), Symbol("name")=>Symbol("name"), Symbol("type")=>Symbol("type"))
const _property_types_ImmutabilityPolicy = Dict{Symbol,String}(Symbol("id")=>"String", Symbol("name")=>"String", Symbol("type")=>"String")
Base.propertynames(::Type{ ImmutabilityPolicy }) = collect(keys(_property_map_ImmutabilityPolicy))
Swagger.property_type(::Type{ ImmutabilityPolicy }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_ImmutabilityPolicy[name]))}
Swagger.field_name(::Type{ ImmutabilityPolicy }, property_name::Symbol) =  _property_map_ImmutabilityPolicy[property_name]

function check_required(o::ImmutabilityPolicy)
    true
end

function validate_property(::Type{ ImmutabilityPolicy }, name::Symbol, val)
end
